### ISSUE TITLE
Reload issue - 

### ISSUE THREAD

**Issue by ClickyMCSMP** [OmegaWeaponDev/OmegaVision#10] opened 2021-11-09 12:42 UTC
### issue-description

Plugin doesn't seem to want to be reloaded with `/nv reload`. Also, I checked my files with yaml error finder, it appears files are fine. /omegavision reload says the plugin reloaded - but doesnt apply my changes.

### Error Messages

https://paste.helpch.at/qokejesuke.bash

### Expected Behaviour

For NV to reload all file configurations to apply my configuration changes.

### Debug Information

https://imgur.com/a/Zk4ECGq

### Logs and Configs

https://paste.helpch.at/zivaherope.shell
https://paste.helpch.at/ocogesirej.makefile

**Comment by OmegaWeaponDev** [comment] 2021-11-09 12:47
Hi, 

Firstly, the reload command is `/omegavision reload`. The error you got from doing `/nv reload` is because that is not a command. (I shall put a check inplace though to stop this error. 

I will also look into the issue about the files not reloading correctly. 

Thanks.

**Comment by OmegaWeaponDev** [comment] 2021-11-10 03:50
Hi,

Please try this version:
[OmegaVision-2.5.0.zip](https://github.com/OmegaWeaponDev/OmegaVision/files/7509683/OmegaVision-2.5.0.zip)

This version should fix the error when you tried `/nv reload` since that isn't a valid command and the `/omegavision reload` command should be fixed.

**Comment by OmegaWeaponDev** [comment] 2021-11-12 00:47
Hi @ClickyMCSMP,

I can happily confirm that I was able to reproduce the issue with files not correctly reloading and have been able to successfully resolve this issue. 

Once some other issues have been resolved and tested I will release the fix in an update.

**Closed by OmegaWeaponDev** 2021-11-12 00:47 UTC
Labels: bug, resolved
